### ISSUE TITLE
After put xenforo file and run docker-composer.yml, and still can't access localhost port 10080

### ISSUE THREAD

**Issue by chornthorn** [luutruong/xenforo2_docker#1]
Please help me!

**Comment by luutruong** [comment]
What is output for `docker ps -a`

**Comment by chornthorn** [comment]
![Screen Shot 2022-03-10 at 7 42 31 PM](https://user-images.githubusercontent.com/36778896/157664019-1223a306-d531-4100-a1b7-bb8285e653b4.png)

**Comment by luutruong** [comment]
Can you check if the port `10080` was open in your side?
